CHANGELOG.md
src/DebugBar/Resources/debugbar.css
src/DebugBar/Resources/debugbar.js
src/DebugBar/Resources/widgets/sqlqueries/widget.css
src/DebugBar/Resources/widgets/sqlqueries/widget.js

- adding some minimize and maximize button next to the close button
- adding the pdo connection name, and build filter on them

usefull button

---

src/DebugBar/Bridge/Propel2Collector.php
tests/DebugBar/Tests/DataCollector/Propel2CollectorTest.php

We can use this collector very easy
```php
$connect = \Propel\Runtime\Propel::getServiceContainer()->getReadConnection();
$debugbar->addCollector(new \DebugBar\Bridge\Propel2Collector($connect));
```

Added propel2 collector and tests

---

src/DebugBar/Bridge/Twig/TraceableTwigEnvironment.php

Made the the getCache method compatible with Twig_Environment getCache Method

Updated the getCache method

---

composer.json

Use PSR-4 without moving files about

---

src/DebugBar/Resources/widgets.css

This allows logging multiple whitespace and whitespace at line start.
With that you can create indendation eg. in Timeline.

Show whitespace in log output

---

src/DebugBar/Resources/widgets/sqlqueries/widget.js

phpdebugbar-widgets-error is a block element

---

src/DebugBar/Bridge/CacheCacheCollector.php
src/DebugBar/Bridge/DoctrineCollector.php
src/DebugBar/Bridge/MonologCollector.php
src/DebugBar/DataCollector/AggregatedCollector.php
src/DebugBar/DataCollector/ConfigCollector.php
src/DebugBar/DataCollector/DataCollector.php
src/DebugBar/DataCollector/ExceptionsCollector.php
src/DebugBar/DataCollector/LocalizationCollector.php
src/DebugBar/DataCollector/MemoryCollector.php
src/DebugBar/DataCollector/MessagesCollector.php
src/DebugBar/DataCollector/PDO/PDOCollector.php
src/DebugBar/DataCollector/PDO/TraceablePDO.php
src/DebugBar/DataCollector/PDO/TraceablePDOStatement.php
src/DebugBar/DataCollector/PDO/TracedStatement.php
src/DebugBar/DataCollector/PhpInfoCollector.php
src/DebugBar/DataCollector/RequestDataCollector.php
src/DebugBar/DataCollector/TimeDataCollector.php
src/DebugBar/DataFormatter/DataFormatter.php
src/DebugBar/DebugBar.php
src/DebugBar/HttpDriverInterface.php
src/DebugBar/JavascriptRenderer.php
src/DebugBar/OpenHandler.php
src/DebugBar/PhpHttpDriver.php
src/DebugBar/RequestIdGenerator.php

I added phpdocs on many functions that had none, and fixed some of the incorrect phpdocs.

PHPDoc Fixes

---

src/DebugBar/DataCollector/PDO/TraceablePDO.php
src/DebugBar/DataCollector/PDO/TraceablePDOStatement.php

Watch issue https://github.com/maximebf/php-debugbar/issues/274

Updated/added comments for PDO Collector

---

README.md

I created a SilverStripe module to integrate the debug bar :-)

Integration with SilverStripe

---

README.md

I've added Grav to the list of integrations as we've been using DebugBar in Grav for the past couple of years.  Thanks for the great project!

Added Grav to integrations

---

src/DebugBar/DataCollector/PDO/PDOCollector.php

so that we can see that a specific measure came from a pdo connection, and which connection that was.

add pdo connection name to time collector

---

docs/base_collectors.md

Update docs for PDOConnector

---

src/DebugBar/DataCollector/TimeDataCollector.php

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maximebf/php-debugbar/329)

Fix PHP 7.1 | "A non well formed numeric value encountered"

---

src/DebugBar/Resources/vendor/highlightjs/styles/github.css

currently these styles will override anything in my application, localizing them to only the debugbar seems like a good solution.

localize hljs's css to phpdebugbar

---

src/DebugBar/Storage/MemcachedStorage.php

Some users may wish to prevent indefinite accumulation of logged data,
especially if the Memcached cluster is shared with other production
data.

Allow setting Memcached item expiration

---

src/DebugBar/DataCollector/PDO/TracedStatement.php
tests/DebugBar/Tests/TracedStatementTest.php

Bugfix getSqlWithParams ReplacementParamsQuery

Bugfix getSqlWithParams ReplacementParamsQuery

---

src/DebugBar/DataCollector/PDO/TracedStatement.php
src/DebugBar/Resources/widgets/sqlqueries/widget.css
src/DebugBar/Resources/widgets/sqlqueries/widget.js
tests/DebugBar/Tests/TracedStatementTest.php

Create feature copy query to clipboard:

Create feature copy query to clipboard

---

src/DebugBar/Storage/RedisStorage.php

Patch increases possible number of records stored and loaded from Redis DB by separating metadata and collector's data and storing them in different hashes. Retrieving is done with HSCAN instead of HGETALL, which causes FatalErrorException with "Allowed memory size of 134217728 bytes exhausted" on around of 2500 records. HSCAN takes records by portions what leads to a little speedup even on small amount or records (about 3-4%) and also allows to work on 7500+ records as well.
Tested for 5 days and still goes well. Current version takes about 10sec to load a request list on ~4500 records set, while this does the same in 0.8sec on 7700+.
Problem is described in barryvdh/laravel-debugbar#417

RedisStorage performance fix

---

src/DebugBar/Resources/debugbar.js

https://github.com/maximebf/php-debugbar/issues/375

Fix maximize-btn then 'phpdebugbar-tab' does't set.

---

src/DebugBar/JavascriptRenderer.php
src/DebugBar/Resources/debugbar.js

Adds support for fetch in addition to xhr (and jquery) #421
Most notably (for me anyway) this gets debugbar working in Apollo-based SPA's and GraphiQL.

Fetch support

---

docs/ajax_and_stack.md

Adds some explanation of the fetch support now available in debugbar

Fetch documentation

---

CHANGELOG.md
src/DebugBar/Bridge/SwiftMailer/SwiftLogCollector.php

New implementation of dump() in SwiftLogCollector

---

README.md

Added Joomla to the list  of Integrations with other frameworks

added Joomla  to the list  of Integrations with other frameworks

---

README.md

I created a Drupal module that inserts debugbar and collects various Drupal-specific information.

Add Drupal module

---

src/DebugBar/JavascriptRenderer.php

Quickfix for PHP 8.1 compatibility. Resolves here the null issues https://github.com/maximebf/php-debugbar/issues/488

Dont use null where string is expected

---

CHANGELOG.md
composer.json

Add Support for `symfony/var-dumper` ^6

---

src/DebugBar/Resources/widgets/templates/widget.css
src/DebugBar/Resources/widgets/templates/widget.js

Hi Dear, 
i made this PR to handle the editor link Which comes from the BE (ViewCollector).
my PR Includes:
- Add JS code that check if there is **editorLink**  variable and display it if present.
- Add  some CSS code.
Hope it will be accepted soon...
Thanks in advance.

[Feat]: viewsTab: handle editor-link 

---

src/DebugBar/Resources/widgets.js

This will allow us to easily customize the presentation of the keys

HtmlVariableList support html on keys

---

composer.json

Add Support for symfony/var-dumper ^7

---

src/DebugBar/DataCollector/PDO/PDOCollector.php

Same as other collectors
https://github.com/maximebf/php-debugbar/blob/27b3c2f2340d429e466d42ebcd47034bf3cd1850/src/DebugBar/DataCollector/MessagesCollector.php#L257-L268
https://github.com/maximebf/php-debugbar/blob/27b3c2f2340d429e466d42ebcd47034bf3cd1850/src/DebugBar/Bridge/MonologCollector.php#L104-L116

Make PDOCollector easy to extend

---

src/DebugBar/DataCollector/PDO/PDOCollector.php

Reverts maximebf/php-debugbar#582 because I'm not sure of the BC break or not here. See #593

Revert "Make PDOCollector easy to extend"

---

demo/pdo.php

Reverts maximebf/php-debugbar#593 see https://github.com/maximebf/php-debugbar/pull/594

Revert "Fix demo PDOCollector name, and update it with 72fea42"

---

src/DebugBar/Resources/widgets/mails/widget.js

Fixes https://github.com/maximebf/php-debugbar/pull/617#pullrequestreview-1931095633

Fix mail body check

---

src/DebugBar/Resources/openhandler.js
src/DebugBar/Resources/widgets.js
src/DebugBar/Resources/widgets/sqlqueries/widget.js
src/DebugBar/Resources/widgets/templates/widget.js

Reduce dependency for jQuery step by step, maybe we can use the Slim build in the shorter future.

Use fetch instead of jQuery ajax

---

demo/bootstrap.php
demo/index.php
src/DebugBar/Resources/debugbar.css
src/DebugBar/Resources/debugbar.js
src/DebugBar/Resources/widgets.js
tests/DebugBar/Tests/Browser/DebugbarTest.php

This combines the dropdown with the dataset tab, so the UI changes minimally (only icon + badge added) but you can easily navigate to the history tab.

Combine dropdown with dataset handler

---

src/DebugBar/Resources/debugbar.css

better readability
This also fixes unnecessary scrollbar in some highlightjs code block

Fix line-height on tabs

---

src/DebugBar/DataFormatter/HasXdebugLinks.php

File linking support was added in CodeLite 17.10.0

Add support for CodeLite links

---

demo/bridge/doctrine/index.php
demo/pdo.php
src/DebugBar/Bridge/DoctrineCollector.php
tests/DebugBar/Tests/Browser/Bridge/DoctrineTest.php
tests/DebugBar/Tests/Browser/PdoTest.php

Fixes https://github.com/maximebf/php-debugbar/pull/257
Also adds tests to the pdo collector, which was already escaped.

Escape doctrine entries

---

.github/workflows/run-integration.yml
.github/workflows/run-tests.yml

This PR updates run-tests.yml and run-integration.yml to add PHP 8.4 to the test matrix.

Update workflow files for CI to test with PHP 8.4

---

src/DebugBar/Resources/debugbar.css

is broken since this change: https://github.com/maximebf/php-debugbar/commit/cd46685df82a370f6682ad92a81adfc44326f438#diff-f8b1773a74ff6db4b152bc60684f28e27084381920026052bac436b09db55d31L173 
@nckrtl

debugbar.css: fix broken CSS

---

src/DebugBar/Resources/widgets/sqlqueries/widget.js

Don't this this is really needed but anyways, according to the spec this works.

Check copy result

---

src/DebugBar/Bridge/DoctrineCollector.php

Fix `array to string converstion`

---

.gitignore

Delete chromedriver file

---

src/DebugBar/DataFormatter/HasXdebugLinks.php

Add cursor editor support

---

src/DebugBar/Resources/debugbar.css
src/DebugBar/Resources/debugbar.js

This is a followup of https://github.com/php-debugbar/php-debugbar/pull/660
https://github.com/user-attachments/assets/6cb0d076-4c3f-4812-a141-28e4f28463ac

Dragging Feature (followup)

---

src/DebugBar/Resources/debugbar.css
src/DebugBar/Resources/debugbar.js

I tested this, and I'm not 100% sure about it. I like the idea but it feels really like and edge case. I can see the appeal of moving the debugbar to the right instead of left, but I think that should be either configurable in the UI or as option.
The dragging has a bit of a downside of keeping the draggable state when switching tabs or something. Not really sure but it doesn't feel reliable yet.

Revert dragging

---

src/DebugBar/Resources/debugbar.js
src/DebugBar/Resources/openhandler.css
src/DebugBar/Resources/openhandler.js

* Copy debugbar theme to openhandler
* TWeak table layout

Fix openhandler theme (#715)

---

src/DebugBar/Resources/debugbar.js

Show the tab when you have both a tab and indicator

Add link for indicator to show tab

---

src/DebugBar/DataCollector/TimeDataCollector.php
src/DebugBar/Resources/widgets.js

Optionally group the Timeline data for aggregates

Group timeline

---

src/DebugBar/JavascriptRenderer.php

Makes it easier to sort widgets without worrying about the defined order

Sort widgets by order

---

src/DebugBar/RequestIdGenerator.php

Always use random_bytes for request ID

---

src/DebugBar/DataCollector/PDO/TracedStatement.php
tests/DebugBar/Tests/TracedStatementTest.php

Fix PHP 8 warning in `TracedStatement::getSqlWithParameters()` when a stream resource was bound.
```
TypeError: mb_check_encoding(): Argument #1 ($value) must be of type array|string|null, resource given
```
This can happen when e.g. [binding `PDO::PARAM_LOB`](docs) to your query.
[docs]: https://www.php.net/manual/en/pdo.lobs.php

Fix warning on resource query parameter

---

src/DebugBar/DataCollector/MessagesCollector.php

Better support on windows
Base on [barryvdh/laravel-debugbar/DataCollector/QueryCollector.php#L351-L368](https://github.com/barryvdh/laravel-debugbar/blob/008dfe9ee0dc2256db2138b96d1062abaf0b3b60/src/DataCollector/QueryCollector.php#L351-L368)

Allow overwriting the trace finder on Messages

---

demo/index.php
src/DebugBar/DataCollector/ObjectCountCollector.php
src/DebugBar/Resources/widgets.css
src/DebugBar/Resources/widgets.js

discussed in https://github.com/php-debugbar/php-debugbar/pull/764#issuecomment-2790966287
On widget both options were added, `badges`, and `summary`

Summary badges in ObjectCountCollector

---

src/DebugBar/DataFormatter/VarDumper/DebugBarHtmlDumper.php

Dump darkmode styles for dumper

---

src/DebugBar/Resources/vendor/highlightjs/highlight.pack.js

Fixes https://github.com/php-debugbar/php-debugbar/pull/704#discussion_r2080456547
Ref.: https://github.com/highlightjs/highlightjs.org/pull/24

Bump highlight.js to 11.11.1, and fix php highlight

---

src/DebugBar/JavascriptRenderer.php

uasort must return comparison result
https://www.php.net/manual/en/function.uasort.php

fix:  control sort applied correctly by control.order

---

phpunit.xml.dist

See https://github.com/symfony/panther/issues/675

Disable devtools on test suite
