src/DebugBar/DataCollector/PDO/TracedStatement.php

Array index works only with positioned (where foo = ?) parameters.
To make named (where foo = :baz) parameters debuggable the name must be defined as key.

Show the real parameter name for prepared queries.

---

src/DebugBar/Resources/widgets.js

Don't round left/width, instead use two decimals.
This improves accuracy of Timeline when more similar sized entries are shown.

Improve accuracy of Timeline

---

src/DebugBar/Resources/debugbar.css

PHPDebugBar showing in `@media print` makes no sense as it's purpose is debug.
This makes easier to test printing pages on debug server.

Hiding PHPDebugBar on @media print

---

src/DebugBar/Resources/debugbar.css
src/DebugBar/Resources/debugbar.js
src/DebugBar/Resources/openhandler.js
src/DebugBar/Resources/widgets.js
src/DebugBar/Resources/widgets/sqlqueries/widget.js

Links have `href` attribute set to `javascript:`, which is not only useless, but unnecessarily shows destination on hover. It's annoying for debugbar, because it takes some place on the screen when we just hover on any tab. HTML5 specification allows anchors with no `href` specified, as mentioned here: http://w3c.github.io/html-reference/a.html#a.attrs.href
The only difference is that they then get standard cursor by default, which is corrected as well by my pull merge.

Remove meaningless hrefs

---

src/DebugBar/Resources/debugbar.css

I'm using debugbar on a website which has a very generous letter-spacing on the `body` element.
Unfortunately that cascades into the debugbar styling, which makes the data very difficult to read.
That being said, the `letter-spacing: normal;` resets the debugbar back to the intended result.

Apply normal letter-spacing

---

src/DebugBar/DataCollector/MessagesCollector.php

This fixes a bug - when extending the DataFormatter its not possible to set the new class as data formatter via collectorInstance->setDataFormatter(...) - it complains about wrong Interface.

Fix for wrong namespace lookup. No clean use possible otherwise.

---

src/DebugBar/Resources/widgets.js

Most of the time I want to see if a file was loaded and I don't really want to bother getting all of the camelCasing when I'm just doing a simple search.
This enables caseless matching in the files collector tab!
However, if caseless searching returns too many results, you can still search with Capitals and get a more narrowed set of results :smile: 
Closes #194.

Enable caseless searching in the "Files" toolbar

---

src/DebugBar/DataCollector/PhpInfoCollector.php

It is important to know how the php is running from cli or a web request. In some frameworks like laravel there is commands features which we also want to know the exception from command line or a web interface.

Added PHP_SAPI in Php data collector

---

src/DebugBar/Resources/debugbar.js

Fixes #149
Check the padding on startup, use that when resizing, to account for sticky footers etc.

Use original padding in calculation

---

src/DebugBar/Resources/debugbar.js

Hello,
this PR fixes problems related to sites that use an absolute footers. In order to better get the idea here are some tests I have made:
http://debugbar.padding.codewizz.com/ - this one is using the old padding-bottom inline style (just try to expand the debugbar, you will see the footer starts to shrink and finally hides under the debugbar panel)
http://debugbar.margin.codewizz.com/ - this one is using the new margin-bottom inline style (at first it looks like the footer is being overlapped but you can scroll down and see all the web content like it should be displayed).
In addition I have added margin-bottom style removal from body once debugbar is closed or minimized. This is especially handy when your front-ender is working on a site and you don't want to toggle debugbar on and …

Offset calculation change to body margin-bottom

---

src/DebugBar/DataFormatter/DataFormatter.php
tests/DebugBar/Tests/DataFormatter/DataFormatterTest.php

It's possible for a `TracedStatement` to have a negative memory delta, which causes the DataFormatter to crash.

Added support for negative numbers in DataFormatter::formatBytes()

---

src/DebugBar/DataCollector/ExceptionsCollector.php

We only want exceptions, so if it's not an exception, convert it to one. We shouldn't rely on the fact that it would be an Error otherwise.

Go with the most semantically correct option

---

composer.json
src/DebugBar/DataCollector/ExceptionsCollector.php

Instead of transforming them to Exceptions, we could still just parse them.
We need to deprecate the public methods, because of the typhints, so implementations can use the new methods instead.
cc @jamiehd @GrahamCampbell

Add Throwables, deprecate exceptions

---

src/DebugBar/Resources/debugbar.css

Fix for issue https://github.com/maximebf/php-debugbar/issues/266
Instead of inheriting text direction, this will force it to be left to right.

forces direction of text to be ltr

---

src/DebugBar/Resources/widgets/sqlqueries/widget.js

The "duplicate" count was in fact the "unique" count.
Before:
After:

change count for unique and duplicated queries

---

src/DebugBar/Resources/debugbar.js

Some headers are unsafe to read (in Chrome), checking all returned headers will prevent these errors. See https://github.com/barryvdh/laravel-debugbar/issues/384

Check for unsafe header

---

src/DebugBar/Resources/debugbar.js

This fixes two problems:
1.  In recomputeBottomOffset, if bodyMarginBottomHeight is NaN, we need
to change that to a 0 before adding so we don’t end up setting
the offset variable to NaN.
2.  We now initialize bodyMarginBottomHeight in the initialize function.
This fixes a bug where bodyMarginBottomHeight gets set to NaN if the
debugbar.js is included in the page header and not the page body
(i.e. before the body element has been loaded).

Fix bodyMarginBottomHeight-related bugs in DebugBar

---

src/DebugBar/DataCollector/TimeDataCollector.php

Sometimes, users of this collector may not add measurements in order of
the start time.  For example, various existing measurement systems may
feed existing measurements into this class via the addMeasure function.
Sort the measurements by start time during collection.  This yields a
nice, chronological view of the measurements, similar to Chrome
DevTools.

TimeDataCollector sorts measurements by start time

---

src/DebugBar/Bridge/Twig/TwigCollector.php

If there aren’t any templates, the twig widget crashes the client.  Fix
the bug by safely checking for null and assuming 0 if so.

Fix front-end crash when there are no twig templates

---

src/DebugBar/Storage/MemcachedStorage.php

The OpenHandler modal returns results in oldest first order by default, changed storage find method so newest entries are at the top.

Added array reverse to find results

---

src/DebugBar/Resources/debugbar.css
src/DebugBar/Resources/openhandler.css
src/DebugBar/Resources/widgets.css
src/DebugBar/Resources/widgets/mails/widget.css
src/DebugBar/Resources/widgets/sqlqueries/widget.css
src/DebugBar/Resources/widgets/templates/widget.css

Use system fonts to match current OS UI chrome for `sans-serif` and
`monospace` fonts, giving a more consistent look with the OS and other
developer tools in the browser.
As as side note, this technique is also used by GitHub.
Also, font-awesome icons on the same line with monospace text are now correctly aligned.
Read more: https://css-tricks.com/snippets/css/system-font-stack/
Here is a screenshot on macOS Sierra:

Use system fonts

---

docs/ajax_and_stack.md
src/DebugBar/JavascriptRenderer.php
src/DebugBar/Resources/debugbar.js
tests/DebugBar/Tests/JavascriptRendererTest.php
tests/DebugBar/Tests/full_init.html

By default, the debug bar will immediately show new AJAX requests. If
your page makes a lot of requests in the background (e.g. tracking),
this constant switching of the active data set can be disruptive to the
debug bar user.
This commit adds an option for disabling this behavior by calling
setAjaxHandlerAutoShow(false) on the JavascriptRenderer, like this:
$renderer = $debugbar->getJavascriptRenderer();
$renderer->setAjaxHandlerAutoShow(false);
When this behavior is disabled, AJAX requests are still available in the
drop-down list, but won’t become active until the user explicitly
selects them.

Add option to not immediately show AJAX requests

---

src/DebugBar/Bridge/Twig/TraceableTwigTemplate.php

Fix for  #330
Twig was unable to check for template being instance of self because Traceable twig template was not extending it.
Please note that since version 2 of twig, Twig_Template does not implement Twig_TemplateInterface  and Twig_TemplateInterface will be removed in version 3.x and thus phpdebugbar should do so.

Fix twig template instance check

---

src/DebugBar/Resources/debugbar.css
src/DebugBar/Resources/debugbar.js

Small fix for badges in tabs.
The problem appears when body element has `display: flex` style so jQuery's `.show()` function add `display="block"` instead of `display="inline"` to badges `span` element.

Fix line breaking for tab badges

---

src/DebugBar/Resources/widgets/sqlqueries/widget.js

The PDO collector assumes that the number of duplicate statements is
equal to the number of total statements minus the number of unique
statement query strings that had more than one query.  This leads to
non-sensical statements like the following:
5 statements were executed, 4 of which were duplicated, 1 unique
when the following statements were executed.  (Assume each letter
represents a particular query)
* A
* A
* B
* C
* D
Clearly there are not 4 duplicate statements under any reasonable
interpretation.  After this code change, it would more correctly say for
the above example:
5 statements were executed, 2 of which were duplicates, 3 unique

Fix incorrect duplicate statement counter in PDO collector

---

src/DebugBar/DebugBar.php

It can be useful to use the PHP Debug Bar from the command line if a
storage layer is configured.  In that scenario, a user would run a PHP
CLI application, then open a web page with the debug bar front-end and
use the open handler to locate the command-line invocation.
However, a problem is that the collect() function assumes that standard
HTTP variables are available - this assumption does not apply when
running from the CLI.  Write a special branch of code for the CLI server
API so that reasonable metadata can be collected for the CLI case.
Without this patch, null method, URI, and IP are logged and it actually
becomes impossible to open the CLI invocation in the open handler - let
alone tell them apart.

Support debug bar collection from command-line

---

src/DebugBar/Resources/debugbar.css
src/DebugBar/Resources/widgets.css

1. The list of messages was missing `padding-bottom`, causing the search box to obscure the bottom message.
1. Explicitly declare styles for text input elements to avoid interference from the containing page’s stylesheet.  (On our site, text input elements had 10px padding, causing the search box to be much larger than the `padding-bottom` margin allowed for.)

Fix misc. style sheet problems with MessagesWidget

---

src/DebugBar/Resources/debugbar.js

If the URI ends with a trailing '/', then the existing code would just show an empty string as the label, which isn't very useful if a page is making lots of varied AJAX calls to URIs that end with trailing slashes.
Fix this by detecting if the URI ends with a trailing '/'.  If it does, then we also include the segment of the URI just prior to the trailing '/'.

Improve formatting of the data set labels

---

docs/data_collectors.md
docs/rendering.md
src/DebugBar/DataCollector/AssetProvider.php
src/DebugBar/JavascriptRenderer.php
tests/DebugBar/Tests/JavascriptRendererTest.php

Add new `inline_css`, `inline_js`, and `inline_head` keys on the `AssetProvider::getAssets()` function.  This allows us to support collectors that require static assets that are not actually saved to a file.
Then, update all the asset functions in `JavascriptRenderer` to support these new keys.
An initial use case for this is supporting the `HtmlDumper` in Symfony’s VarDumper.  `HtmlDumper` only provides the styles and scripts in inline HTML form.  The static assets can be customized based on some configuration properties available on the `HtmlDumper` class.  One can actually view the CSS/JS as a long PHP string/heredoc embedded in the `HtmlDumper.php` source code.  They are only accessible via the `getDumpHeader` function, which returns the CSS/JS in a combined HTML string.
- Example of …

Enable AssetProvider to support inline assets

---

src/DebugBar/Resources/widgets.css
src/DebugBar/Resources/widgets.js

When showing backtraces, it’s useful to:
1. Show line numbers for each line of contextual code.
1. Highlight the line from the backtrace.
This commit adds the functionality to `widgets.js`/`css` for doing this.
Screenshot of functionality with highlight.js:
Screenshot of functionality without highlight.js:

Add line number and line highlighting support to createCodeBlock

---

src/DebugBar/Resources/debugbar.css

Some existing user-provided stylesheets on the page might have a
different default color for code and pre elements; set it to black:
similar to what is already being done with the root div.phpdebugbar
style.

Set code/pre color to black

---

docs/data_formatter.md
src/DebugBar/DataCollector/DataCollector.php
src/DebugBar/DataFormatter/DebugBarVarDumper.php
src/DebugBar/Resources/debugbar.css
tests/DebugBar/Tests/DataFormatter/DebugBarVarDumperTest.php

The Symfony VarDumper component includes an `HtmlDumper` that dumps variables in a rich HTML format that allows for expanding and collapsing individual tree nodes in the dumped variable.  This makes it much more practical to navigate large/deep variables that have been dumped.
`DebugBarVarDumper` provides a Debug Bar-friendly wrapper around the VarDumper component.  It’s intended as an alternative to `DataFormatter::formatVar` to enable this rich HTML interface.  It provides for:
* Debug Bar-friendly styles for the VarDumper HTML.
* Implements `AssetProvider` for returning VarDumper static assets (requires users of `JavascriptRenderer` to support inline assets).
* Simplifies/wraps `VarCloner` and `HtmlDumper` function calls for cloning and dumping variables in a Debug Bar environment. …

Introduce DebugBarVarDumper for HTML variable dumping

---

src/DebugBar/Storage/MemcachedStorage.php

The `find` function for memcached storage is not very efficient when a large number of debug bar frames have been stored over time.  Improve the performance by:
1. Retrieve no more items than absolutely necessary.  (i.e. don’t retrieve every last possible item and then slice the result array.)
1. Use bulk retrieval `getMulti` function with memcached.

Improve efficiency of memcached find

---

src/DebugBar/DataCollector/MemoryCollector.php
src/DebugBar/DataCollector/PDO/TracedStatement.php

The memory_get_usage and memory_get_peak_usage functions have a
$real_usage parameter.  Update the MemoryCollector and PDOCollector
collectors to allow the user to choose which type of memory usage to
gather.
To recap, when $real_usage is set (and previously this was the
hard-coded default), PHP returns the amount of memory allocated from the
operating system by the PHP memory manager.  This is typically done in
large chunks of memory and is not very granular.
When $real_usage is cleared, PHP returns the amount of memory the user’s
application has actually allocated from the PHP memory manager.
Clearing $real_usage has useful application especially for the
PDOCollector.  As an example, a query that returns only a few rows will
often say that zero bytes were used when $real_usage is set. …

Add real usage option to memory collection

---

src/DebugBar/RequestIdGenerator.php
src/DebugBar/RequestIdGeneratorInterface.php

Implementers of `RequestIdGeneratorInterface::generate()` need to be sure that each call to `generate()` will return a unique ID.
This could fail to happen in the existing implementation if `microtime()` returns the same value on two successive `generate()` calls that come within the same microsecond.  For example, in a tight ID-generating loop.  It was unlikely, but now it is practically impossible.
Additionally, implementers should make sure that the return value is not all-numeric to avoid any mixed data types when IDs are used as keys in PHP arrays.  (For example, numeric IDs could result in bugs when `array_merge` is used.)

RequestIdGeneratorInterface now requires a unique ID on each call

---

docs/base_collectors.md
src/DebugBar/DataCollector/MessagesCollector.php
src/DebugBar/Resources/widgets.css
src/DebugBar/Resources/widgets.js
tests/DebugBar/Tests/DataCollector/MessagesCollectorTest.php

Use the new `DebugBarVarDumper` class to support dumping variables in interactive collapsible HTML; the new `useHtmlVarDumper()` function will enable this.
Since this will require users to handle the new inline assets provided by the `JavascriptRenderer`, make this dumping format optional and default to the old behavior for now.

Update MessagesCollector to support HTML var dumping

---

docs/base_collectors.md
src/DebugBar/DataCollector/ConfigCollector.php
src/DebugBar/DataCollector/RequestDataCollector.php
src/DebugBar/Resources/widgets.css
src/DebugBar/Resources/widgets.js
tests/DebugBar/Tests/DataCollector/ConfigCollectorTest.php

Introduce a new `HtmlVariableListWidget` that is similar to `VariableListWidget` but for variables with HTML contents.
Update the collectors that use the existing `VariableListWidget` to use `DebugBarVarDumper` to dump the variables using the VarDumper `HtmlDumper`. Because many debug bar users may not yet support inline static assets, default to use the old `VariableListWidget` for now.
Updated collectors:
* `ConfigCollector`
* `RequestDataCollector`
Screenshot of `RequestDataCollector`:

Use new HtmlVariableListWidget with collectors

---

src/DebugBar/DataFormatter/DebugBarVarDumper.php
src/DebugBar/DataFormatter/VarDumper/DebugBarHtmlDumper.php

The top-level debug bar style is `phpdebugbar` not `debugbar`.  This was preventing rendered HtmlDumper dumps from styling correctly.
Screenshot of the broken behavior this pull request fixes:

Fix broken top-level style name

---

src/DebugBar/Resources/widgets/sqlqueries/widget.js

if the pdo collector is empty, the script will be throw error

fixed in ajax mode the pdo collector maybe empty

---

src/DebugBar/Storage/RedisStorage.php

Debugbar output with RedisStorage and Redis 3.0.6 (can't test others) now comes in random order. Likely
sorted by hash. The patch solves the problem. Code is reworked to be close to a similar one in FileStorage.

Added sorting for RedisStorage

---

.travis.yml
src/DebugBar/DataCollector/PhpInfoCollector.php

Commit 1fd5af22 introduces array syntax that is incompatible with PHP 5.3, which this package still states support for. This PR is a patch to undo this.
Also switching to precise on Travis (default is quickly becoming trusty) to ensure PHP 5.3 compatibility.
I'd suggest releasing a new semver compatible version that removes PHP 5.3-5.5 support at some stage.

Fix remove square bracket array declaration for PHP 5.3 compatibility

---

src/DebugBar/Resources/debugbar.css

PhpStorm picked this up while inspecting our codebase.

Unit of measurement is redundant in CSS

---

src/DebugBar/Resources/widgets/templates/widget.js

Sometimes `tpl.xdebug_link` is defined, but has a null value, which causes a check for `.ajax` to throw an error.

Check that xdebug_link isn't null

---

src/DebugBar/DataCollector/PDO/TracedStatement.php
tests/DebugBar/Tests/TracedStatementTest.php

I've maintained a [project](https://github.com/noahheck/E_PDOStatement) that performs similar behavior to what occurs in the `TracedStatement` (generating a string from the parameterized query with the bound arguments put in place into it), so I've seen some of the things to beware of when offering this functionality. Here's a synopsis of the issues and how I work around them:
If a value to be replaced back into the string contains a substring that looks like a regex back reference (e.g. `$1`), the `preg_replace` function looks to facilitate that:
i.e. password_hash function may produce something like this:
```
$2y$10$Xs/oqD0cVCb7hM1suoAD/Oqf4tlm5suTb8IsczDTnttiWUtHsb5ay
```
but the interpolated query value ends up like this:
```
y$Xs/oqD0cVCb7hM1suoAD/Oqf4tlm5suTb8IsczDTnttiWUtHsb5ay
``` …

Traced statement interpolation fixes

---

src/DebugBar/Resources/widgets.js

This aggregates all time measures with the same label and displays the count and total duration in a table on the Timeline tab. 
I am not sure this will be useful for others but it has helped me a lot to debug performance issues when there are many small steps involved and it is not clear which of the small steps are adding up most. 
Without this code would have to be rearranged to fit into a single measurement.

Aggregate Timeline Measures

---

src/DebugBar/DataCollector/PDO/TracedStatement.php
tests/DebugBar/Tests/TracedStatementTest.php

Before fix it : 
select *  from geral.person p
left join geral.contract c
on c.id_person = p.id_person
where c.status = <1> and
p.status <> :status;
`
public function testRepeadParamsQuery()
{
$sql = 'select *
from geral.person p
left join geral.contract c
on c.id_person = p.id_person
where c.status = :status and 
p.status <> :status';
$params = array(
':status' => 1
);
$traced = new TracedStatement($sql, $params);
$expected = 'select *
from geral.person p
left join geral.contract c
on c.id_person = p.id_person
where c.status = <1> and 
p.status <> <1>';
$result = $traced->getSqlWithParams();
$this->assertEquals($expected, $result);
}`

 Bug fix repead params sql 

---

src/DebugBar/Resources/debugbar.js

fixes #386
i had the same issue, very annoying indeed. firefox doesn't crash. i tried to disable the hardware acceleration in chrome, seemed promising, but did't solve that.
i suppose this PR is not the quality for a permanent fix (sorry for that), but i hope someone more skilled can improve the PR.

truncate the filename part in the dataset title if its too long

---

src/DebugBar/DataCollector/PDO/TraceablePDO.php
src/DebugBar/DataCollector/PDO/TraceablePDOStatement.php
src/DebugBar/DataCollector/PDO/TracedStatement.php

I found some parts of TraceablePDO-related code a bit confusing (using it for extra tasks on my project), so I'm clearing it up here :)
I would also like to ask if it's needed to keep all those repeated methods inside TraceablePDO; if `__call()` already forwards all calls, why pollute the new class file with meaningless forwarding methods?

Improving some PHPDoc types and array notation for readability

---

src/DebugBar/Resources/debugbar.css

Since it can be resized both up and down.
**Before**
**After**

Using ns-resize cursor

---

src/DebugBar/Resources/openhandler.css

When the underlying website uses a white font color (dark theme...) the content is not visible.

Force open handle font color

---

docs/base_collectors.md

ExceptionsCollector->addException() is deprecated since #281.

docs: Replace deprecated ExceptionsCollector->addException() by addThrowable()

---

demo/bridge/twig/index.php
docs/bridge_collectors.md
src/DebugBar/Bridge/Twig/TraceableTwigEnvironment.php
src/DebugBar/Bridge/Twig/TraceableTwigTemplate.php
src/DebugBar/Bridge/Twig/TwigCollector.php

The reasoning behind this merge is to get rid of the `TwigCollector`, which seems to work only for `twig/twig <2`.
Since there is an alternative `TwigProfileCollector` which seems to work throughout v1 and v2 of Twig, I have updated the demo to use that instead.
And also cleaned the bridge documentation to reflect the now absent `TwigCollector`.
This fixes #423. WDYT @barryvdh?

Deprecate TwigCollector and friends

---

src/DebugBar/Bridge/MonologCollector.php

This would fix an issue who uses `MonologCollector` with `Monolog` v2.
There is an issue when you try to use `Bridge/MonologCollector` because the abstract method signature has changed in `Monolog` v2. The diff: https://github.com/Seldaek/monolog/commit/06143b03e5c1598bfa6c6df65432010da0ecc28b#diff-d1d031ebe96084844fb53eb650bc404eR50
However, this change is a bit tricky. Because `Monolog` in v2 has increased PHP dependency to `^7.2`, also added those void return type hints. So this change could break things for people who uses `MonologCollector` with PHP version lower than 7.1.

Add void return type hint for MonologCollector::write()

---

composer.json

Added Symfony 5 support. No changes in https://github.com/symfony/symfony/blob/5.0/UPGRADE-5.0.md regarding VarDumper so it should be good to go
#SymfonyHackday

Symfony 5 support added

---

src/DebugBar/Resources/debugbar.js

Fixing a JS error preventing the debug bar to be displayed on Internet explorer.

Fixing JavaScript error (Internet Explorer)

---

src/DebugBar/Resources/debugbar.js

I think doing nothing here is fine; `response` isn't available in the catch.

Remove broken fetch catch

---

src/DebugBar/Resources/debugbar.js

When a new dataset is loaded, the layout can change. Trigger the resize to make it fit directly. Fixes #445

Trigger resize on new dataset

---

src/DebugBar/DataCollector/TimeDataCollector.php
tests/DebugBar/Tests/DataCollector/TimeDataCollectorTest.php

The goal to this PR is to be able to have the return value from the measure function.
Currently to obtain the same result we have to add a reference in the called closure as:
```
$debugbar->measure(
$label,
function () use (&$output) {
$output = 'AnyReturnValue';
}
);
var_dump($output);
```
So now we can just do: 
```
$output = $debugbar->measure(
$label,
function () {
return 'AnyReturnValue';
}
);
var_dump($output);
```

Add return value to measure() function.

---

src/DebugBar/DataCollector/PDO/TraceablePDO.php

PHP 8.0: TraceablePDO adding query arguments

---

src/DebugBar/DataCollector/MessagesCollector.php

This is an optional part of the PSR-3 spec: https://www.php-fig.org/psr/psr-3/#12-message
It allows injecting values in log messages like this:
```php
$logger->error('User {username} does not exist.', ['username' => $username]);
```

Add support for PSR-3 message placeholders

---

src/DebugBar/DataCollector/ExceptionsCollector.php
src/DebugBar/Resources/widgets.js

This PR adds a new `useHtmlVarDumper()` method on `ExceptionsCollector` (similar to the one that exists on `ConfigCollector` or `MessagesCollector`).
It makes the stack trace easier to inspect by making it a dumped array instead of a long string.
I had to disable the click event that toggles the surrounding lines because it would be triggered by inspecting the stack trace.

Allow useHtmlVarDumper() on ExceptionsCollector

---

docs/base_collectors.md
src/DebugBar/DataCollector/PDO/PDOCollector.php

It's easy to auto-wrap the PDO object inside the collector. As the wrapped object is only useful to the collector, it seems this responsibility should be internal.

Makes the PDO wrapper transparent

---

src/DebugBar/DataFormatter/DebugBarVarDumper.php
src/DebugBar/DataFormatter/VarDumper/DebugBarHtmlDumper.php

Reset the dumpHeader by adding a new method, because we cannot set `null` anymore, since typehints have been added (see https://github.com/maximebf/php-debugbar/issues/474)

Fix vardumper #474

---

src/DebugBar/DataCollector/MessagesCollector.php

Fixes #476, builds upon #465
The PSR-3 spec describes logging strings, but this worked before in Debugbar. 
This is only affected for the PSR-3 methods, not addMessage.

Check log messages before interpolate

---

composer.json

psr/log2 is essentially psr/log1 with new php8 syntax but as long as this pkg is locked into psr/log1 this leads to an incompatible situations like the one described here: https://github.com/barryvdh/laravel-debugbar/issues/1244
Also if some pkgs require psr/log2, the psr/log1 lock will make this unnecessarily incompatible.

updated psr/log acceptable mayor version

---

src/DebugBar/DataFormatter/DataFormatterInterface.php

I was getting strange warnings like this in my logs:
```
2021-02-06T17:55:18+01:00 [info] User Deprecated: The "DebugBar\DataFormatter\DataFormatter::formatVar()" method will require a new "mixed $var" argument in the next major version of its interface "DebugBar\DataFormatter\DataFormatterInterface", not defining it is deprecated.
```
Turns out it was caused by this docblock having the wrong variable name.

Wrong variable name in docblock

---

src/DebugBar/DataFormatter/DataFormatter.php
src/DebugBar/JavascriptRenderer.php

Discovered in Joomla  running under php 8.1
- `Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated `
- `Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated `
- `Deprecated: Implicit conversion from float -INF to int loses precision`

php 8.1 deprecations

---

src/DebugBar/DataFormatter/DataFormatter.php

This fixes a PHP 8.1 bug "Deprecated: Implicit conversion from float -INF to int loses precision in vendor/maximebf/debugbar/src/DebugBar/DataFormatter/DataFormatter.php

PHP 8.1 fix in DataFormatter.php for "Implicit conversion from float-INF to int loses precision"

---

src/DebugBar/Bridge/MonologCollector.php

In monolog 3, write method now accepts a LogRecord object (https://github.com/Seldaek/monolog/commit/22c8b19358e916c52f1d2170d44e172152de7c25) instead of an array. The PR makes the debugbar collector compatible with that signature.

Fix monolog 3 compat

---

src/DebugBar/DataCollector/PDO/TracedStatement.php
tests/DebugBar/Tests/TracedStatementTest.php

In my application, I noticed that on seemingly random occurrences, parameters would be repeated when replacing them in the SQL query string: (notice that they display fine in the table under the query, but the first one is inserted in all 3 locations)
This PR fixes this issue.
Looking at open issues here, this seems to be the same issue as https://github.com/maximebf/php-debugbar/issues/457, but this problem arises for me without using `BETWEEN` statements... 🤔 
I have added a test, and all tests are passing.

Fix random instances of SQL queries having params repeated

---

src/DebugBar/DataCollector/PDO/TracedStatement.php

In PHP8.1, htmlentities doesn't accept null as valid first argument; cast any equivalent-to-false into string before passing it to htmlentities.

Always provide htmlentities with a string, for PHP8.1

---

src/DebugBar/Resources/debugbar.js

Sometimes, when we are using TS in project, the event listener receives a URL object instead string:
https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L17144
When this happens, the following error appears:
The code changed in this PR prevents this error.

Fix event listener when URL is object

---

src/DebugBar/DataCollector/PDO/TracedStatement.php

Parameter `$preparedId` is optional with a default value of null, but the return type of the getter method `getPreparedId` is set to string triggering a `TypeError`.

fix: preparedId is nullable

---

src/DebugBar/DataCollector/PDO/TraceablePDO.php

If the PDOTraceableDataCollector is enabled and no database calls happen to be made in a request, PHP 8.1 emits a fatal error, e.g.,
```
<b>Fatal error</b>: Uncaught TypeError:
DebugBar\DataCollector\PDO\TraceablePDO::getAccumulatedStatementsDuration():
Return value must be of type float, null returned in
vendor/maximebf/debugbar/src/DebugBar/DataCollector/PDO/TraceablePDO.php:251
```
The same error occurs in getMemoryUsage() and getPeakMemoryUsage().
Adding an initial value of 0 to `array_reduce()` corrects the problem.
Fixes #522.

Add initial values to traceable PDO array_reduce()

---

src/DebugBar/Storage/RedisStorage.php

When using Redis Cluster with phpredis, the class is not 'Redis', but 'RedisCluster' and the code only checks for the first one. This change fixes the `Undefined array key 0` that appears in this situation.

Fix error when using RedisCluster with phpredis

---

src/DebugBar/DataCollector/PDO/TraceablePDOStatement.php
tests/DebugBar/Tests/DataCollector/AggregatedCollectorTest.php
tests/DebugBar/Tests/DataCollector/TimeDataCollectorTest.php
tests/DebugBar/Tests/DebugBarTestCase.php
tests/DebugBar/Tests/OpenHandlerTest.php
tests/DebugBar/Tests/Storage/FileStorageTest.php

- Use of "parent" in callables is deprecated
- Creation of dynamic properties is deprecated since php 8.2 (used in some test)

Fix PHP 8.2 deprecations

---

src/DebugBar/JavascriptRenderer.php

**Short Version:**
This PR fixes csp errors caused by <script> tags without a nonce generated by HtmlDumper.
**Long version:**
`JavaScriptRenderer::render()` adds content using `JavaScriptRenderer::getAddDatasetCode()` with data from `JavaScriptRenderer::getData()`, which returns data from `JavaScriptRenderer::collect()`.
`JavaScriptRenderer::collect()` essentially does this:
```
foreach ($this->collectors as $name => $collector) {
$this->data[$name] = $collector->collect();
}
```
For the both the request collector from maximebf/debugbar (default_request) and laravel-debugbar, the collect() function uses `$data[$key] = $this->getVarDumper()->renderVar($GLOBALS[$var]);` to render the variables.
`getVarDumper()` by default returns a `DebugBarVarDumper` instance. …

Fix content security policy failure due to <script> tags without nonce generated by HtmlDumper

---

bower.json

This fixes the content security policy errors generated by jquery not propagating the nonce to nodes it creates. (As mentionen in #529).
I have tested this for regressions.

Fix content security policy errors by upgrading jquery (fixes #529)

---

src/DebugBar/DataCollector/DataCollector.php

- `addXdebugReplacements` allows easily adding an array of replacements without removing existing ones
- PhpDoc for `setXdebugReplacement` added

add `addXdebugReplacements` option

---

src/DebugBar/DataCollector/ExceptionsCollector.php

This gives us the option to customize the exception trace.
For example: 
- remove/normalize the path of the remote server files, or remove the vendor files from entries
- `getTraceAsString` can be changed to [php-elog/jTraceEx.php](https://github.com/tox2ik/php-elog/blob/master/src/jTraceEx.php)

Add custom trace formatter helper

---

docs/base_collectors.md

Also: why is the website not up to date with the docs ?
There is `;` instead of `,` in http://phpdebugbar.com/docs/base-collectors.html#others
Line 125 of this file

docs: Fix class name missing full import

---

src/DebugBar/Resources/widgets.js

Closes #448
```diff
- aggregate.label +
+ $('<i />').text(aggregate.label).html() +
```

(fix) XSS in timeline

---

src/DebugBar/Resources/debugbar.js
src/DebugBar/Resources/widgets.js

Add name to the <input> and <select> fields
This is to remove certain Chrome "improvement" notices like:
"A form field element has neither an id nor a name attribute. This might prevent the browser from correctly autofilling the form."
Note: Some still remain but as far as I can tell those are coming from VarDumper not this repo.

Add names to inputs

---

src/DebugBar/DataCollector/ExceptionsCollector.php

avoid sending `traceAsString` when already html trace exists, it is not necessary to send both at the same time
https://github.com/maximebf/php-debugbar/blob/30f65f18f7ac086255a77a079f8e0dcdd35e828e/src/DebugBar/Resources/widgets.js#L580-L583
remove base path from trace paths
Closes #555

normalize file paths on exceptions traces

---

src/DebugBar/Resources/debugbar.js

Added catch to promise for window.fetch wrapper to avoid "Uncaught (in promise) DOMException: The user aborted a request." errors.
This is required to not trigger React's error handler which looks very confusing.
Related issue: https://github.com/barryvdh/laravel-debugbar/issues/1348

Added catch to promise for window.fetch wrapper

---

src/DebugBar/DataFormatter/HasXdebugLinks.php

@barryvdh hi
in some editors something comes `home.blade.php:`, If there is no line number this generates an error 
add line 1 by default so that the editor can open the file, example: `home.blade.php:1`

Fix file not exists by setting line default 1 on editor links

---

src/DebugBar/DataCollector/PhpInfoCollector.php

In case of custom indicators it clarifies

More informative tooltip

---

src/DebugBar/DataCollector/MessagesCollector.php

When `isHtmlVarDumperUsed()` is false, we have this
But, when `isHtmlVarDumperUsed()` is true, all data is expanded by default
With this change, it is easier to find the log we are looking for, by the file, line, etc
Also as an independent method it is possible to make other customizations based on `$message` data, just by extending the class

Avoid expanded values on MessagesCollector

---

src/DebugBar/Resources/widgets.js
src/DebugBar/Resources/widgets/sqlqueries/widget.js

This could be added to more collectors probably, but basically: 
If a selection range is active, prevent the click behavior. Especially useful for thinks like copying paths etc.

Do not click when selection is active

---

demo/iframes/iframe1.php
demo/iframes/iframe2.php
demo/iframes/index.php
demo/index.php
src/DebugBar/Resources/debugbar.js

Alternative to https://github.com/maximebf/php-debugbar/pull/452#issuecomment-1936976144
>We needed a way to add them to the debugbar. (a bit like it happens with ajax+headers).
The debugbar is opened in the top frame, and when something happens inside the iframes, the changes are being added to the top-level debugbar.
Some iframes may be hidden or small, this PR propagates data from iframes to the top main debugbar and also it prevents size errors caused by small iframes(the inside smaller iframe change web storage like height, that affects the main debugbar)

Keeps only the main debugbar functionality on iframes

---

src/DebugBar/DataCollector/ObjectCountCollector.php
src/DebugBar/Resources/widgets.css
src/DebugBar/Resources/widgets.js

Allow array to be used as value to make it easier to extend functionality. Fallback to the string variant

Use xdebug_link in html variables

---

src/DebugBar/Bridge/SwiftMailer/SwiftMailCollector.php

- Issue introduced on #617
After #617, SwiftMailCollector stop showing messages body preview,
Now `html` array key is needed
https://github.com/maximebf/php-debugbar/blob/0b407703b08ea0cf6ebc61e267cc96ff7000911b/src/DebugBar/Bridge/Symfony/SymfonyMailCollector.php#L65-L66

Fix html body mail on SwiftMailCollector

---

src/DebugBar/Resources/debugbar.js

This changes the resize calculation to check the children in the header directly, and include margins.
Also re-check if a dataset is loaded.

Fix resize

---

src/DebugBar/JavascriptRenderer.php
src/DebugBar/Resources/debugbar.js
tests/DebugBar/Tests/full_init.html

I don't think it is useful anymore. We're using bindToXhr for years in laravel-debugbar without issues.

Feat deprecate bindtojquery

---

.gitignore
tests/DebugBar/Tests/DataCollector/AggregatedCollectorTest.php
tests/DebugBar/Tests/DataCollector/TimeDataCollectorTest.php
tests/DebugBar/Tests/DebugBarTest.php
tests/DebugBar/Tests/DebugBarTestCase.php

- Improve some PHPUnit assertions.
- Let the `.phpunit.result.cache` file be on `.gitignore` file and this is generated by `PHPUnit 9.x.` version.

Improve assertion and ignore cached PHPUnit file

---

src/DebugBar/JavascriptRenderer.php

Thank you for your developing!
I found the debug bar is not displayed correctly when the query string contains "<!--<script>" (confirmed with maximebf/debugbar v1.22.3).
This pull request fixes the issue. Please check it out.
Pattern 1: sample query string
```
?<!--<script>
```
Pattern 2: sample code
```
$debugbar["messages"]->addMessage("<!--<script>");
```

Fix not rendering correctly in some cases

---

src/DebugBar/Resources/widgets.css

Closes https://github.com/barryvdh/laravel-debugbar/issues/1644
> In the `HtmlVariableListWidget` widget the alignment breaks when you the vardumper output as value and a xdebug link:
> 
> ![image](https://github.com/user-attachments/assets/43ee592f-a3d1-459d-8020-b9fbdd6490ff)
> 
> The links are pushed down by the vardumper element and disappear behind the gray rows.
Fixed

Fix link alignment issue

---

src/DebugBar/Resources/widgets/sqlqueries/widget.js

When clicking on the editor link in the query tab, the backtrace sub table opens unnecessarily, it's annoying
Fix for ajax urls too

Prevent query backtrace showing on editor link click

---

src/DebugBar/Bridge/DoctrineCollector.php

Version: [v1.22.4](https://github.com/maximebf/php-debugbar/releases/tag/v1.22.4)
Change causing crash: Escape doctrine entries by @barryvdh in https://github.com/maximebf/php-debugbar/pull/657
Fixes error:
```php
Error (E_ERROR):	htmlentities(): Argument #1 ($string) must be of type string, DateTime given
File:	/.../vendor/maximebf/debugbar/src/DebugBar/Bridge/DoctrineCollector.php
Line:	87
```
If passing Datetime instance to Doctrine ORM QueryBuilder.
```php
$doctrineOrmQueryBuilder
->andWhere("item.date_from <= :date_from")
->setParameter('date_from', new \DateTime($array['date_from']), Types::DATE_MUTABLE);
```
Also fixes argument output if array is given.

Fix parameter output if parameter is Datetime or array [v1.22.4]

---

src/DebugBar/Resources/widgets/sqlqueries/widget.css
src/DebugBar/Resources/widgets/sqlqueries/widget.js

Instead of the alert, toggle the copy button with a similar icon for 2 seconds, to indicate success.

Enable copy, tweak icon

---

src/DebugBar/JavascriptRenderer.php
src/DebugBar/Resources/debugbar.js
tests/DebugBar/Tests/JavascriptRendererTest.php

This will hide empty collectors, until the collector is actually filled using any data.
This can be useful for less-used collectors without filling up te screen.
Note:
- It is not hidden when empty, to keep a more consistent flow when using ajax etc.
- it's not using the badge because not every collector uses a badge
Not sure if it's worth creating a config option for.

Hide empty collectors until used

---

src/DebugBar/Bridge/DoctrineCollector.php

Version: [v1.23.0](https://github.com/maximebf/php-debugbar/releases/tag/v1.23.0)
Improved output when zero is parameter.

Fix parameter output if parameter is zero [v1.23.0]

---

demo/bootstrap.php
src/DebugBar/Bridge/CacheCacheCollector.php
src/DebugBar/Bridge/MonologCollector.php
src/DebugBar/Bridge/PropelCollector.php
src/DebugBar/Bridge/Twig/TimeableTwigExtensionProfiler.php
src/DebugBar/Bridge/Twig/TraceableTwigEnvironment.php
src/DebugBar/DataCollector/PDO/PDOCollector.php
src/DebugBar/DataCollector/PDO/TracedStatement.php
src/DebugBar/DebugBar.php

In PHP 8.4, implicit nullable parameter types are deprecated; see also https://wiki.php.net/rfc/deprecate-implicitly-nullable-types.
This MR changes occurrences of this pattern.
See also https://github.com/barryvdh/laravel-debugbar/pull/1632.

Replace implicit nullable types in parameter declarations

---

src/DebugBar/DataFormatter/HasXdebugLinks.php

The URL scheme for Nova is incorrect; per Panic's recent post (https://social.panic.com/@panic/112689904216756608) this now uses the correct format. This is tested (briefly) with Laravel for confirmation.
(N.B.: I am assuming the "nova" setting for editors here is indeed meant to be Panic Nova and not another Nova I'm unfamiliar with!)

Fix Panic Nova link template

---

src/DebugBar/Resources/debugbar.css
src/DebugBar/Resources/debugbar.js

Make it easier to show more extensive tooltips

Allow tooltip to show as key/value list

---

src/DebugBar/Resources/widgets.js

For example the Laravel error page has hljs now, which doesn't contain SQL. So that will fail otherwise.

Check if hljs has language

---

composer.json

https://getcomposer.org/doc/04-schema.md#keywords
> Note: Some special keywords trigger composer require without the --dev option to prompt users if they would like to add these packages to require-dev instead of require. These are: dev, testing, static analysis.

Add dev keyword

---

src/DebugBar/Resources/widgets.css

Fix icon on symfony HtmlDumper

---

src/DebugBar/DataCollector/PDO/TracedStatement.php
src/DebugBar/Resources/widgets.js
tests/DebugBar/Tests/TracedStatementTest.php

Fix PHP 8 warning in `TracedStatement::getSqlWithParameters()` when null was bound
Since PHP 8.0, [built-in functions like `strtr()` will emit a warning when passing `null` to required string parameters](docs):
```
strtr(): Passing null to parameter #1 ($string) of type string is deprecated
```
This can happen when e.g. binding `PDO::PARAM_NULL` to your query.
[docs]: https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.null-not-nullable-internal

Fix warning on null query parameter

---

src/DebugBar/Resources/widgets.js

Similar to the badge, add the widget with 
```php
public function getWidgets()
{
return array(
"time" => array(
"icon" => "clock-o",
"tooltip" => "Request Duration",
"map" => "time.duration_str",
'link' => 'timeline',
"default" => "'0ms'"
),
"timeline" => array(
"icon" => "tasks",
"widget" => "PhpDebugBar.Widgets.TimelineWidget",
"map" => "time",
"default" => "{}"
),
'timeline:tooltip' => array(
'map' => 'time.tooltip',
'default' => '{}'
),
);
}
```

Map tooltip data

---

src/DebugBar/JavascriptRenderer.php
src/DebugBar/Resources/debugbar.js

Gives the option to defer the loading of the dataset. This gives the change for a request to write more data (eg. terminable middleware) before loading, and make the requests smaller. 
Next step would be to only load or render when the debugbar is open..

Allow dataset to defer loading instead of passing all the data

---

src/DebugBar/JavascriptRenderer.php

I tried to test this functionality and I always get that the file does not exist, and in the sources the file is saved when doing `getData()`, with this change it works for me, or am I doing something wrong?
https://github.com/php-debugbar/php-debugbar/blob/917a032fbab522e0b82232a12fd1eeb439020919/src/DebugBar/DebugBar.php#L248-L252
Ref #723

Fix defer data loading

---

src/DebugBar/Resources/widgets/sqlqueries/widget.js

This allows that if the query is too large or the window is too small the buttons stay at the top, currently they go to the bottom making their access more difficult in large queries or with many line breaks

Query code after buttons block

---

src/DebugBar/Resources/widgets.js

This prevents it from becoming illegible in the cases described
Before this change
After this change

Avoid LF, \t, multiple spaces on timeline

---

src/DebugBar/Resources/debugbar.js

Some collectors handle `count` key, 
and if it is zero it should be hidden, or not?
https://github.com/php-debugbar/php-debugbar/blob/3f589bbbaed53039d9699702c2908148647c27a1/src/DebugBar/DataCollector/MessagesCollector.php#L213
https://github.com/php-debugbar/php-debugbar/blob/3f589bbbaed53039d9699702c2908148647c27a1/src/DebugBar/DataCollector/ObjectCountCollector.php#L71
https://github.com/php-debugbar/php-debugbar/blob/3f589bbbaed53039d9699702c2908148647c27a1/src/DebugBar/Bridge/Symfony/SymfonyMailCollector.php#L76
https://github.com/php-debugbar/php-debugbar/blob/3f589bbbaed53039d9699702c2908148647c27a1/src/DebugBar/Bridge/SwiftMailer/SwiftMailCollector.php#L56
https://github.com/php-debugbar/php-debugbar/blob/3f589bbbaed53039d9699702c2908148647c27a1/src/DebugBar/Bridge/MonologCollecto …

Hide cero count tabs

---

docs/data_collectors.md

Seems that the class suggested for `Renderable` interface is wrong in descriptive text, but right in sample code.

fixing typo in documentation about Renderable interface

---

src/DebugBar/DataCollector/ExceptionsCollector.php

It would be great to be able to collect the other types of errors that don't stop the script from running.
**Example:**
```php
$cadena = "";
$cadena--;
```

OPT-IN Start collecting warnings, notices and deprecations on ExceptionsCollector

---

src/DebugBar/Resources/debugbar.css

For some reason it seems to break the tooltips, 
I haven't found any other problem, but it's better to revert it.

Revert aa370d0

---

src/DebugBar/DataCollector/RequestDataCollector.php

Code usage:
```php
$debugbar['request']->hideSuperglobalKeys('_COOKIE', ['PHPSESSID', 'MY_COOKIE']);
```
Same as Whoops
[Whoops/Handler/PrettyPageHandler.php#L807-L833](https://github.com/filp/whoops/blob/075bc0c26631110584175de6523ab3f1652eb28e/src/Whoops/Handler/PrettyPageHandler.php#L807-L833)
[Whoops/Handler/PrettyPageHandler.php#L86-L94](https://github.com/filp/whoops/blob/075bc0c26631110584175de6523ab3f1652eb28e/src/Whoops/Handler/PrettyPageHandler.php#L86-L94)

Blacklist keys on Request for hide sensitive data

---

src/DebugBar/Resources/widgets.css

If the value is a large array, the name makes `vertical-align: middle;`, its usefulness is lost

Name of the parameter easier to read in the timeline

---

src/DebugBar/Resources/debugbar.css

From 
To
Closes https://github.com/barryvdh/laravel-debugbar/issues/1771

fix symfony var-dumper css on dark theme

---

src/DebugBar/Resources/widgets.js

It's easier to read when there is more than one exception. Most of the time it is not necessary to see all the traces
Before 
After

Compact symfony var dumper, and better text

---

src/DebugBar/Resources/widgets.js

The file name must be prepended, on small windows or wide array messages, the filename is pushed down

Fix filename position on message collector

---

src/DebugBar/Resources/debugbar.css

[php-debugbar](https://github.com/php-debugbar/php-debugbar) is hidden under other components,
so I add 1 to the z-index and it works
> z-index: 9999999999;
**Source:** [filp/whoops/src/Whoops/Resources/css/whoops.base.css#L17C14-L17C24](https://github.com/filp/whoops/blob/075bc0c26631110584175de6523ab3f1652eb28e/src/Whoops/Resources/css/whoops.base.css#L17C14-L17C24)

Fix debugbar z-index

---

src/DebugBar/Resources/widgets.js

For example int value `0` becomes `''`

Fix falsy values en keys (HtmlVariableListWidget)

---

src/DebugBar/Storage/RedisStorage.php

For PhpRedis >= 6.1.0 cursor MUST be null for the first run of the `[hsz]scan`
Solution inspired by the one in the Laravel Framework
```php
$defaultCursorValue = match (true) {
$connection instanceof PhpRedisConnection && version_compare(phpversion('redis'), '6.1.0', '>=') => null,
default => '0',
};
```
https://github.com/laravel/framework/blob/f18288f30c3c0007df6d20474c72ea2bed1af4d8/src/Illuminate/Cache/RedisStore.php#L316-L319

fix for PhpRedis >= 6.1.0 in RedisStorage

---

demo/index.php
src/DebugBar/DataCollector/ObjectCountCollector.php
src/DebugBar/Resources/widgets.css
src/DebugBar/Resources/widgets.js

On #609 the consistency of the data array was broken, the array can be variable
So, sometimes can be `{Class: 0}` other `{Class: {value: 0}}`
This PR now uses `{Class: {value: 0}}` format always, 
The option to have more counts if necessary is also added,
now could be `{Class: {count_1: 0, count_2: 0, count_n: 0}}`
Before 
After
---
I was looking for a generic widget that creates a table but I couldn't find it, so I created a new generic one: `PhpDebugBar.Widgets.TableVariableListWidget`
with a key map we could make tables, for example
Keymap
```json
{"count_1": "Count 1", "count_2": "Count 2", "count_3": "Count 3"}
```
With object
```json
{
"class_1": {"count_1": 23, "count_2": 87, "count_3": 15, "other_val": "val"},
"class_2": {"count_1": 54, "count_2": 31, "count_3": 76, "other_val": …
```

Multiple counters on ObjectCountCollector, generic widget TableVariableListWidget

---

composer.json

If I understood correctly `self.version` would also be useful for this case
https://getcomposer.org/doc/04-schema.md#replace
>You should then typically only replace using `self.version` as a version constraint, to make sure the main package only replaces the sub-packages of that exact version, and not any other version, which would be incorrect.
Maybe closes #779

Fix version replace

---

src/DebugBar/DataCollector/PDO/PDOCollector.php

>- #790
>
> ```php
> $debugbar['pdo']->setSlowThreshold(100); // time on ms
> ```
To make it work with milliseconds you have to divide by 1000

Fix #790 - Slow threshold highlight on queries
